# Generated by Django 4.1.2 on 2025-02-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Disease', models.CharField(max_length=20)),
                ('bp', models.CharField(max_length=10)),
                ('sugar', models.IntegerField()),
                ('oxygen', models.IntegerField()),
            ],
        ),
    ]
