# Generated by Django 4.1.2 on 2025-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanalWindow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Disease',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
