# Generated by Django 4.1.2 on 2025-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanalWindow', '0002_patient_info_status_alter_patient_info_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='Name',
            field=models.CharField(default='Confidential', max_length=20),
        ),
    ]
