# Generated by Django 4.1.2 on 2025-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanalWindow', '0007_patient_info_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='sugar',
            field=models.CharField(max_length=10),
        ),
    ]
